from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run(args: list[str]) -> int:
    return subprocess.call(args, cwd=ROOT)


def clean() -> int:
    patterns = ["__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", "htmlcov"]
    files = [".coverage", "coverage.xml", "pytestdebug.log"]
    for directory in list(ROOT.rglob("*")):
        if directory.is_dir() and directory.name in patterns:
            shutil.rmtree(directory, ignore_errors=True)
    for file_name in files:
        path = ROOT / file_name
        if path.exists():
            path.unlink()
    for pyc in ROOT.rglob("*.pyc"):
        pyc.unlink(missing_ok=True)
    for pyo in ROOT.rglob("*.pyo"):
        pyo.unlink(missing_ok=True)
    print("Cleaned local test/cache artifacts.")
    return 0


def release_check() -> int:
    """Run the full source-release gate without leaving forbidden artifacts behind."""
    rc = clean()
    if rc:
        return rc

    rc = run([sys.executable, "-m", "compileall", "-q", "app", "web_portal", "scripts", "tests"])
    if rc:
        clean()
        return rc

    # compileall intentionally creates __pycache__/*.pyc files.  The release
    # verifier must inspect the same clean tree that will be packaged, so clean
    # generated bytecode before calling the verifier.
    rc = clean()
    if rc:
        return rc

    rc = run([sys.executable, "-B", "scripts/verify_release.py"])
    if rc:
        return rc

    rc = run([sys.executable, "scripts/smoke_test_processor.py", "--self-check"])
    if rc:
        return rc

    rc = run([sys.executable, "scripts/run_sample_dataset_checks.py"])
    if rc:
        return rc

    return clean()



def elite_check() -> int:
    """Run source release gate plus full regression and coverage tests."""
    rc = release_check()
    if rc:
        return rc
    rc = run([sys.executable, "-m", "pytest", "-q", "--no-cov"])
    if rc:
        return rc
    rc = run([sys.executable, "-m", "pytest", "-q"])
    if rc:
        return rc
    return clean()

def main(argv: list[str]) -> int:
    commands = {
        "test": lambda: run([sys.executable, "-m", "pytest", "-q", "--no-cov"]),
        "test-cov": lambda: run([sys.executable, "-m", "pytest", "-q"]),
        "verify": lambda: run([sys.executable, "-B", "scripts/verify_release.py"]),
        "smoke": lambda: run([sys.executable, "scripts/smoke_test_processor.py", "--self-check"]),
        "clean": clean,
        "compile": lambda: run([sys.executable, "-m", "compileall", "-q", "app", "web_portal", "scripts", "tests"]),
        "preflight": lambda: run([sys.executable, "scripts/preflight_windows.py"]),
        "sample-check": lambda: run([sys.executable, "scripts/run_sample_dataset_checks.py"]),
        "release-check": release_check,
        "elite-check": elite_check,
    }
    if len(argv) != 2 or argv[1] not in commands:
        print("Usage: python scripts/dev.py <command>")
        print("Commands: " + ", ".join(sorted(commands)))
        return 2
    return commands[argv[1]]()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
