# Auto-split from app.py for readability. Executed by app.py in application globals.

# ─────────────────────────────────────────────────────────────
# Defaults
# ─────────────────────────────────────────────────────────────
DEFAULT_SETTINGS = {
    "company_name": "M-GROUPS INFRA PROJECTS",
    "registered_name": "MGROUPS INFRA PROJECTS",
    "tagline": "Registered Civil Engineering & Infrastructure Services Enterprise",
    "hero_title": "Civil & Infrastructure Project Execution",
    "hero_subtitle": "M-GROUPS INFRA PROJECTS supports civil engineering, municipal infrastructure, site execution, and project coordination works across Tamil Nadu.",
    "short_description": "Tamil Nadu-based registered infrastructure and civil works enterprise serving Kanyakumari, Nagercoil, and wider Tamil Nadu project requirements.",
    "phone": "",
    "whatsapp": "",
    "public_phone_label": "Phone number is hidden for privacy. Please use the contact form for enquiries.",
    "email": "mgroupsinfraprojects@gmail.com",
    "address": "2/5-1A, North Street, Erachakulam, Nagercoil, Kanniyakumari, Tamil Nadu - 629901",
    "map_embed": "",
    "facebook": "",
    "instagram": "",
    "linkedin": "",
    "logo_path": "uploads/m-groups-logo.jpeg",
    "seo_title": "M-GROUPS INFRA PROJECTS | Registered Civil & Infrastructure Works in Tamil Nadu",
    "seo_description": "M-GROUPS INFRA PROJECTS is a registered Tamil Nadu civil and infrastructure services enterprise with Udyam, GST, experience certificates, contractor registration documents, and project documentation.",
    "og_image": "uploads/m-groups-logo.jpeg",
    "business_area": "Kanyakumari, Nagercoil and Tamil Nadu",
    "service_areas": "Kanyakumari\nNagercoil\nKanniyakumari District\nTamil Nadu\nDindigul\nTirunelveli\nThoothukudi",
    "homepage_section_order": "trust_strip\ncredentials\nservice_areas\nabout\nservices\nstats\nprojects\nwhy\ncta",
    "google_business_url": "",
    "notification_email": "mgroupsinfraprojects@gmail.com",
    "smtp_from_name": "M-GROUPS Website",
    "udyam_registration": "UDYAM-TN-09-0060986",
    "gstin": "33DDOPK4939J1Z2",
    "enterprise_type": "Micro Enterprise",
    "business_commencement": "02/12/2020",
    "major_activity": "Services; civil engineering and infrastructure-related activities",
    "credential_note": "Udyam, GST, experience certificate and contractor registration documents are available for verification. Sensitive personal, tax, invoice and legal documents are not displayed publicly.",
    "experience_documents": "5+",
    "contractor_registrations": "2",

    # Visibility controls. Admin can decide what appears publicly.
    "show_phone_public": "0",
    "show_whatsapp_public": "0",
    "show_email_public": "1",
    "show_address_public": "1",
    "show_registered_name_public": "1",
    "show_udyam_public": "1",
    "show_gstin_public": "1",
    "show_enterprise_type_public": "1",
    "show_business_commencement_public": "0",
    "show_major_activity_public": "1",
    "show_credentials_section": "1",
    "show_trust_strip": "1",
    "show_service_areas_section": "1",
    "show_about_section": "1",
    "show_services_section": "1",
    "show_stats_section": "0",
    "show_projects_section": "1",
    "show_why_section": "1",
    "show_cta_section": "1",
    "show_gallery_nav": "1",
    "show_service_area_nav": "1",
    "show_contact_nav": "1",
    "show_footer_contact": "1",
    "show_footer_credentials": "1",
    "show_whatsapp_float": "0",
    "show_hero_logo_panel": "1",
    "show_hero_metrics": "0",
    "show_project_placeholder_images": "0",

    # Editable labels and section text.
    "hero_badge_label": "Civil & Infrastructure Project Execution",
    "hero_cta_primary": "Request Consultation",
    "hero_cta_secondary": "View Projects",
    "trust_item_1": "Udyam Registered",
    "trust_item_2": "GST Registered",
    "trust_item_3": "Experience Documents",
    "trust_item_4": "Contractor Records",
    "trust_item_5": "Site Execution",
    "credentials_eyebrow": "Verified Business Details",
    "credentials_title": "Registered company profile.",
    "credentials_link_text": "View credentials →",
    "service_areas_eyebrow": "Service Areas",
    "service_areas_title": "Local service pages for better client discovery.",
    "service_areas_all_label": "All Areas →",
    "about_eyebrow": "About Company",
    "about_title": "Reliable execution for civil and infrastructure works.",
    "about_link_text": "Read company profile →",
    "services_eyebrow": "Services",
    "services_title": "What We Do",
    "services_link_text": "All services →",
    "projects_eyebrow": "Works",
    "projects_title": "Recent Projects",
    "projects_link_text": "View all →",
    "image_pending_text": "Image will be added soon",
    "stats_years_label": "Years Since Business Commencement",
    "stats_experience_label": "Experience / Work Records",
    "stats_contractor_label": "Contractor Registration Records",
    "stats_gst_label": "Registered Enterprise",
    "why_eyebrow": "Why Choose Us",
    "why_title": "Disciplined site work, clear coordination, dependable delivery.",
    "why_card_1_title": "Quality Workmanship",
    "why_card_1_text": "Structured execution with supervision, material checks, and finishing discipline.",
    "why_card_2_title": "Project Coordination",
    "why_card_2_text": "Labour, vendors, materials, timelines, and site progress managed from one workflow.",
    "why_card_3_title": "Safety First",
    "why_card_3_text": "Better site behaviour, controlled work areas, and responsible execution practices.",
    "why_card_4_title": "Transparent Updates",
    "why_card_4_text": "Clients receive practical status updates and requirement clarification before delay becomes a problem.",
    "cta_title": "Need civil or infrastructure project support?",
    "cta_text": "Send your work details. The team can review the requirement and contact you.",
    "cta_button_text": "Contact Now",
    "contact_page_title": "Contact Us",
    "contact_page_intro": "Send your project requirement with location, scope, and timeline. The enquiry will be stored in admin and can trigger email notification when SMTP is configured.",
    "contact_card_title": "Business Contact",
    "contact_form_title": "Send Enquiry",
    "footer_company_heading": "Company",
    "footer_contact_heading": "Contact",

    # Appearance controls.
    "heading_font": "Montserrat",
    "body_font": "Manrope",
    "nav_font": "Manrope",
    "primary_color": "#0D1F35",
    "secondary_color": "#C4822A",
    "accent_color": "#E8A046",
    "header_bg_color": "#0D1F35",
    "footer_bg_color": "#07121F",
    "body_bg_color": "#FFFFFF",
    "soft_bg_color": "#F5F8FC",
    "card_bg_color": "#FFFFFF",
    "text_color": "#1C2E3F",
    "muted_text_color": "#5A7089",
    "line_color": "#D8E6F0",
    "button_text_color": "#FFFFFF",
    "container_width": "1160px",
    "card_radius": "20px",
    "button_radius": "11px",
    "hero_title_size": "clamp(2.35rem,4.7vw,4.1rem)",
    "section_title_size": "clamp(1.8rem,3vw,2.6rem)",
    "body_text_size": "16px",
    "custom_css": "",
    "privacy_policy": "This website collects enquiry details submitted through the contact form only for business communication. Sensitive registration, GST, tax, invoice and legal documents are used only for internal verification and are not published in full on the public website.",
    "terms_text": "Information on this website is based on available company registration and project documentation. Project pricing, timelines, and commitments are confirmed only through formal quotation, work order, invoice, or agreement.",
}
DEFAULT_SERVICES = [
    ("Civil Engineering Works", "Civil engineering and infrastructure-related works supported by registered Udyam activity classifications and project documentation.", "building", 1),
    ("Municipal Infrastructure Support", "Execution support for municipal infrastructure works including documented overhead tank-related construction activity in Nagercoil Municipal Corporation.", "road", 2),
    ("Waterways / Civil Infrastructure", "Civil engineering services aligned with registered activity categories covering waterways, harbours, river works, and other civil engineering projects.", "water", 3),
    ("Site Execution & Coordination", "Labour coordination, material movement, site supervision, progress tracking, and practical project execution support.", "clipboard", 4),
    ("Contractor & Compliance Documentation", "Support for maintaining contractor registration, experience certificates, invoice records, GST and project documentation for tender/business verification.", "file", 5),
    ("Renovation & Maintenance Works", "Repair, improvement, and maintenance support for civil structures, sites, and related infrastructure requirements.", "tools", 6),
]


APPEARANCE_FIELDS = [
    "heading_font", "body_font", "nav_font", "primary_color", "secondary_color", "accent_color",
    "header_bg_color", "footer_bg_color", "body_bg_color", "soft_bg_color", "card_bg_color",
    "text_color", "muted_text_color", "line_color", "button_text_color", "container_width",
    "card_radius", "button_radius", "hero_title_size", "section_title_size", "body_text_size", "custom_css",
    "hero_badge_label", "hero_cta_primary", "hero_cta_secondary",
    "trust_item_1", "trust_item_2", "trust_item_3", "trust_item_4", "trust_item_5",
    "credentials_eyebrow", "credentials_title", "credentials_link_text",
    "service_areas_eyebrow", "service_areas_title", "service_areas_all_label",
    "about_eyebrow", "about_title", "about_link_text",
    "services_eyebrow", "services_title", "services_link_text",
    "projects_eyebrow", "projects_title", "projects_link_text", "image_pending_text",
    "stats_years_label", "stats_experience_label", "stats_contractor_label", "stats_gst_label",
    "why_eyebrow", "why_title", "why_card_1_title", "why_card_1_text", "why_card_2_title", "why_card_2_text",
    "why_card_3_title", "why_card_3_text", "why_card_4_title", "why_card_4_text",
    "cta_title", "cta_text", "cta_button_text", "contact_page_title", "contact_page_intro", "contact_card_title", "contact_form_title",
    "footer_company_heading", "footer_contact_heading",
]


APPEARANCE_STYLE_LABELS = [(field, field.replace("_", " ").title(), True) for field in APPEARANCE_FIELDS]

VISIBILITY_FIELDS = [
    "show_phone_public", "show_whatsapp_public", "show_email_public", "show_address_public",
    "show_registered_name_public", "show_udyam_public", "show_gstin_public", "show_enterprise_type_public",
    "show_business_commencement_public", "show_major_activity_public", "show_credentials_section", "show_trust_strip",
    "show_service_areas_section", "show_about_section", "show_services_section", "show_stats_section",
    "show_projects_section", "show_why_section", "show_cta_section", "show_gallery_nav", "show_service_area_nav",
    "show_contact_nav", "show_footer_contact", "show_footer_credentials", "show_whatsapp_float", "show_hero_logo_panel",
    "show_hero_metrics", "show_project_placeholder_images",
]


# Field-level public visibility controls.
# These are deliberately separate from content values: admin can store a value privately and decide whether it is visible publicly.
SETTINGS_FIELD_LABELS = [
    ("company_name", "Company Name", True),
    ("tagline", "Tagline", True),
    ("hero_title", "Hero Title", True),
    ("hero_subtitle", "Hero Subtitle", True),
    ("short_description", "Short Description", True),
    ("phone", "Phone", False),
    ("whatsapp", "WhatsApp", False),
    ("public_phone_label", "Phone Privacy Message", True),
    ("email", "Email", True),
    ("notification_email", "Notification Email", False),
    ("address", "Address", True),
    ("business_area", "Business Service Area", True),
    ("service_areas", "Service Areas", True),
    ("registered_name", "Registered Name", True),
    ("enterprise_type", "Enterprise Type", True),
    ("udyam_registration", "Udyam Registration", True),
    ("gstin", "GSTIN", True),
    ("business_commencement", "Business Commencement", False),
    ("experience_documents", "Experience Documents Count", True),
    ("contractor_registrations", "Contractor Registrations Count", True),
    ("major_activity", "Major Activity", True),
    ("credential_note", "Credential Note", True),
    ("seo_title", "SEO Title", True),
    ("seo_description", "SEO Description", True),
    ("google_business_url", "Google Business Profile URL", True),
    ("map_embed", "Google Map Embed", True),
    ("privacy_policy", "Privacy Policy", True),
    ("terms_text", "Terms Text", True),
    ("facebook", "Facebook", True),
    ("instagram", "Instagram", True),
    ("linkedin", "LinkedIn", True),
    ("logo_path", "Logo", True),
]

ABOUT_FIELD_LABELS = [
    ("short_description", "Short Description", True),
    ("full_description", "Full Company Description", True),
    ("mission", "Mission", True),
    ("vision", "Vision", True),
    ("core_values", "Core Values", True),
    ("experience_summary", "Experience Summary", True),
    ("years_experience", "Years Experience", False),
    ("completed_projects", "Completed Projects", False),
    ("active_projects", "Active Projects", False),
    ("team_members", "Team Members", False),
]

SERVICE_FIELD_LABELS = [
    ("title", "Service Title", True),
    ("icon", "Icon / Category Label", True),
    ("description", "Description", True),
    ("image_path", "Image", True),
]

PROJECT_FIELD_LABELS = [
    ("title", "Project Title", True),
    ("location", "Location", True),
    ("category", "Category", True),
    ("status", "Status", True),
    ("year", "Year", True),
    ("client_type", "Client Type", True),
    ("site_area", "Site / Area", True),
    ("duration", "Duration", True),
    ("project_value", "Project Value", False),
    ("description", "Short Overview", True),
    ("image_path", "Main Image", True),
    ("scope_of_work", "Scope of Work", True),
    ("challenge", "Challenge", True),
    ("solution", "Execution Approach", True),
    ("outcome", "Outcome", True),
]

GALLERY_FIELD_LABELS = [
    ("title", "Gallery Title", True),
    ("caption", "Caption", True),
    ("image_path", "Image", True),
]

FIELD_VISIBILITY_GROUPS = {
    "settings": SETTINGS_FIELD_LABELS,
    "about": ABOUT_FIELD_LABELS,
    "service": SERVICE_FIELD_LABELS,
    "project": PROJECT_FIELD_LABELS,
    "gallery": GALLERY_FIELD_LABELS,
}

